spring.application.name=TaskManagementSystem

# Data Source
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=${SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${SHOW_SQL}

# JWT
venn.jwt.base64-secret=${JWT_SECRET}
venn.jwt.access-token-validity-in-seconds=${JWT_ACCESS_EXPIRE}
venn.jwt.refresh-token-validity-in-seconds=${JWT_REFRESH_EXPIRE}